### ISSUE TITLE
Display all magazine search options without the extra inputs

### ISSUE THREAD

**Issue by Pankakke** [hariettem/Artemis#109]
**Is your feature request related to a problem? Please describe.**
Currently if you go to search for a magazine you will only see the magazines that you subscribe to. If you wish to see magazines that you don't subscribe to you have to add a space to your typed search and then hit "Find magazine with.."

**Describe the solution you'd like**
I'd like to see the search display all matching magazines from the get go or allow you to hit return/enter in order to view the rest of the not subscribed results. This would remove the two extra inputs currently needed to see the full results. 

**Additional context**
This is the current search process 
https://github.com/hariettem/Artemis/assets/138167591/af63425b-21cf-45ac-b21c-fa4ca8cc86bd

**Comment by Prouvaire** [comment]
> allow you to hit return/enter in order to view the rest of the not subscribed results

Absolutely. I'm not sure if the current behaviour is an iPhone or Apollo convention (have never used either) but on Android you would definitely expect to kick off the search when you press the Enter key. On Artemis pressing Enter on the magazine search screen currently does nothing. Having to press the "Find magazines with <your search term>..." text to initiate the search is counter-intuitive as the "Find magazines with..." looks like a purely informational message (ie "this is what will happen when you press Enter") rather than an element that actually does something.

I also agree that what would be even better (not sure if this is technically possible though) is if Artemis kicked off a search on both subscribed _and_ non-subscribed magazines as soon as you started typing (or, let's say, after the third character). Joey for Reddit does this and it's a time saver and intuitive.

**Comment by XiaoKe89** [comment]
Could also work to maybe have two tabs in the magazine section that share the search bar. The first one will only display results from your subscriptions but switching to the second one would show results from everywhere

**Comment by hariettem** [comment]
fixed. tho having two modes (like tabs) is cool. for sure file a ticket if interested in that request

**Comment by Prouvaire** [comment]
> Could also work to maybe have two tabs in the magazine section that share the search bar. The first one will only display results from your subscriptions but switching to the second one would show results from everywhere

Could perhaps also use a single tab with subscribed magazines pushed to the top and/or marked with an icon or similar visual treatment. This would simplify the user interface IMO.
