### ISSUE TITLE
Maintain Post/Comment Sort Order

### ISSUE THREAD

**Issue by NonITExpert** [hariettem/Artemis#155]
Every time I open the app and view my subscribed posts in Home, sort order has been reset to "hot" as default. I end up having to reset to 'new'.

Allow user to set and save sort order for both posts and comments in settings, so it is "set it and forget it".

**Comment by LauraLangdon** [comment]
Came here to open an issue for this if there wasn't one already, so a big +1 from me!

**Comment by its-yourmom** [comment]
+1 from me too… if there was a way to sort the comments from oldest to newest that would make my day! Thanks again for everything your doing to make this app the best ever! ❤️

**Comment by RheingoldRiver** [comment]
Hey @NonITExpert this seems to be fixed now - there is no need to save it, it simply remembers when you restart. (Though not sure about when you update, but probably.)

And @its-yourmom this seems to be available (oldest).

Gonna close this, if it's not working on one of your devices can you open a new ticket as a bug since it should be implemented now?
