### ISSUE TITLE
App frequently does a ‘soft logout’

### ISSUE THREAD

**Issue by VasyaSovari** [hariettem/Artemis#318]
**Describe the bug**

When the app hasn’t been launched for a while it still appears to be logged in but doesn’t update the timeline. Pulling down to refresh content looks like it’s working, but doesn’t. The Refresh button throws up an error.

This can be resolved by manually logging out and back in again.

the behaviour is consistent

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. alpha.1]

**Additional context**

**Comment by hariettem** [comment]
This is related to kbin not having an official API.  There's been an increase the past few days, trying to see what can be done. But, mainly dependent on the API coming out.

Will make sure to catch this when loading posts, to notify user, like when voting.

**Comment by Daleeburg** [comment]
May be related to #309

**Comment by stephen304** [comment]
I think I've had a session expire when making a comment too - I've lost a few comments because it says loading and then loading goes away but the post compose drawer is still there (and in going to re-login I ended up abandoning the compose box). Hopefully the API will be the end of sessions expiring all the time because I get "instance logged you out" messages within 30 minutes of logging in (it used to seem even worse on the web on kbin.social where like 5 minutes after logging in I would be logged out again)

**Comment by hariettem** [comment]
Just an FYI, I got preview access to API on a test instance. So working on an update to use official API. Hopefully by the time I’m done it comes out! One or two weeks.

When I got time, will keep making autologin back feature work more reliably. Just strap for time in the meantime.

**Comment by hariettem** [comment]
fixed with 0.2.0
