### ISSUE TITLE
Artemis crashes on launch, hangs on splash screen

### ISSUE THREAD

**Issue by lloptyr** [hariettem/Artemis#369]
**Describe the bug**

**To Reproduce**
1. Open Artemis
2. The app loads for a brief moment
3. Crash occurs, splash screen displays and hangs

**Expected behavior**
App opens and loads home screen

**Screenshots**
https://github.com/hariettem/Artemis/assets/56057248/1f7f3358-dee6-404e-8863-1dbc4df85369

**Smartphone (please complete the following information):**
 - Device: [Galaxy S9]
 - OS: [Android]
 - Version [10]

**Comment by RheingoldRiver** [comment]
Hey,

A couple questions:

1. What version of Artemis do you have? Is this the public beta? Or are you using an APK  from the closed beta?
2. Do you still have any APK versions installed? Did they previously work?
3. Do you have any other Fediverse applications installed that might be interfering with Artemis? (e.g. always open fediverse links with lemmy, etc)

Thanks so much for reporting!

**Comment by lloptyr** [comment]
1 & 2: I only have the public beta, no apks
3: my only other fedi client is Megalodon, which I dont believe has any priority with lemmy links, but I dont know that for sure

Thank you for replying. Also, I have reinstalled Artemis, rebooted my phone and cleared both my phone's memory cache and the app cache in attempts to fix it

**Comment by RheingoldRiver** [comment]
yeah I don't think that should affect anything.

Thanks for the extra information! afaik we haven't gotten any other report like this, FWIW it's definitely not specifically tied to your OS or phone, because I have the exact same phone & OS as you, and I'm running it without an issue, and have been since alpha.

I'm gonna hold off on prioritizing this and see if we get any more reports like this. Can you join the Discord if you're not already there? https://discord.gg/mqcQuERsTW

**Comment by lloptyr** [comment]
I just joined before making this actually. I did some searching beforehand and hadn't seen any similar reports, which was what prompted me to file one. Usually im pretty content to wait till something is sorted. I appreciate you reaching out so quickly.

**Comment by lloptyr** [comment]
Was finally able to get back in, through deleting the app data (apparently cache and data are different). The app now only crashes if I try to set the theme to "dark" from "system default"
