### ISSUE TITLE
Magazine Sidebar Missing

### ISSUE THREAD

**Issue by justinferrell** [hariettem/Artemis#99]
**Is your feature request related to a problem? Please describe.**
Unless I am missing it, there is currently no way to view the sidebar (description, rules, full URL, etc.) for a magazine. 

**Describe the solution you'd like**
Could you add an icon in the navigation bar, next to the sorting icon, that opened up the sidebar in a drawer that slid in from the right?

**Describe alternatives you've considered**
An alert or something similar, some kind of modal, could also work. You could use a gesture shortcut instead of an icon in the navigation bar but I'm not sure how discoverable it would be.

**Comment by lvndr-dev** [comment]
Following Apollo established design there would be an option menu top right, which would show options for the magazine to subscribe, filter, or view the sidebar.

**Comment by thesoloist-1** [comment]
if I may add a couple thoughts to this. The Apollo feature is always a great option, but sometimes a click to open the list and then another click to open the side bar can be mildly inconvenient. By adding an option to swipe left on the right edge of the screen to view the magazine sidebar (when you're on the magazines front page) could make it easier and quicker to view. That would likely only be active if left/right gestures are turned off in order to avoid conflict.  

Another option could be to show the header and magazines banner at the top of the magazines page. Right below the header could be a swipe-able horizontal list that has all the options available like in the image @lvndr-dev posted.

**Comment by lvndr-dev** [comment]
> By adding an option to swipe left on the right edge of the screen to view the magazine sidebar

It more or less depends on the margins we get for swiping areas. There a lot of swipe zones for specific input: up/down/boost votes, reply, page forward, page back, and what else we might consider. 
In my opinion, the ellipses menu next to the sorting button is the most elegant solution. 
It is visible, unambiguous, and expected - no need to reinvent the wheel in this case.

**Comment by thesoloist-1** [comment]
Simple is better indeed I agree. But in regards to swiping I don’t see it having much conflict when gestures are turned off. Works as intended in Apollo. 

Example: https://github.com/hariettem/Artemis/assets/97246028/cf4e3eaa-6bcd-4ec3-8bbb-0f5f929a856c

**Comment by lvndr-dev** [comment]
> But in regards to swiping I don’t see it having much conflict when gestures are turned off.

I agree! It is a viable option and we should definitely consider it for UI/UX. It should not be difficult to implement, I presume.
The difference between Apollo and Artemis is in relation to kbin/fediverse though: we may need some more space for different icons/options/navigation, and that might conflict with swipes.

**Comment by hariettem** [comment]
This is partially implemented. Will roll out soon-ish. For now it's a dropdown menu (where sub button is today). Slide from right is something I wanna do too.
